package com.TaskFlow.TaskService.dto;

import com.TaskFlow.TaskService.enums.TaskPriority;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.util.Set;
import java.util.UUID;

@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class TaskCreateRequest {

    @NotBlank(message = "Task title is required")
    @Size(max = 255, message = "Title cannot exceed 255 characters")
    private String title;

    private String description;

    @NotNull(message = "Project ID is required")
    private UUID projectId;

    // Optional - a task might be unassigned at creation
    private UUID assigneeId;

    @NotNull(message = "Reporter ID is required")
    private UUID reporterId;

    @NotNull(message = "Priority is required")
    private TaskPriority priority;

    private LocalDate dueDate;

    // A list of Label UUIDs from the Label Service
    private Set<UUID> labelIds;

    // NOTE: We do not pass `taskNumber` or `status` here.
    // `taskNumber` is generated by the Service layer, and `status` defaults to TODO.
}